2018-09-02 15:28:23,329 Log.py [line:31] INFO: 成功打开测试用例
2018-09-02 15:28:23,341 Log.py [line:31] INFO: 测试用例1 test1接口执行失败
2018-09-02 15:28:23,360 Log.py [line:31] INFO: 测试用例2 test2接口执行成功
